### PR TITLE
Update Travis file reference

### PR DESCRIPTION
**Pull request by shadyvb**
Ref https://github.com/humanmade/product-dev/issues/880

### CODE REVIEW

**Review by roborourke — APPROVED** [review]

**Comment by roborourke** [comment]
Worth backporting to v10? Can you do the labels and merges while I go through the rest of these?

**Comment by shadyvb** [comment]
I think we should backport them, yes, otherwise we didn't do much 😅 because Travis will then use the old config version on each version branch.

**Comment by shadyvb** [comment]
🤦 the config changes was only introduced in v10, so that's the only applicable version to backport to.

**Comment by shadyvb** [comment]
Seems like the build is failing still even with the -W flag.. digging..

**Comment by shadyvb** [comment]
Going with:

`- cd $HOME/test-root && composer require -W "$ALTIS_PACKAGE:dev-${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} as ${jq '.packages[] | select (.name==\"$ALTIS_PACKAGE\") | .version' composer.lock | sed -e 's/\"//g;s/\$/9/'`"`

This adds a 9 to the patch version so it is installable.

**Comment by roborourke** [comment]
If I try that locally I get `dev-master` so when working on the `master` branch this would give us `dev-master9` by the looks of it. Need a more complex regex to only append 9 if it's a semver tag that's found.

**Comment by shadyvb** [comment]
Wouldn't the version in CI always be a proper semver though ?

**Comment by roborourke** [comment]
No not if it's a PR against `master` as `altis/skeleton`:

https://github.com/humanmade/altis-skeleton/blob/master/composer.json#L5-L11

**Comment by shadyvb** [comment]
I see, will update.

**Comment by shadyvb** [comment]
Seems like `/^\d/q` would quite the replacement if the pattern match, #TIL !

**Comment by shadyvb** [comment]
`for i in dev-master 10.0.3; do echo $i | sed -e 's/"//g;/^dev/q;s/$/9/'; done` this seems to work as expected.

**Pull request merged**
