### PR TITLE
30 consistent naming of ab testing

### PR DESCRIPTION
**Pull request by jazzsequence**
Replace "AB tests" with "A/B tests"

### CODE REVIEW

**Comment by roborourke** [comment]
This should be based off the master branch and then backported to the v6 branch using the label

**Comment by jazzsequence** [comment]
done

**Review by roborourke — APPROVED** [review]

**Comment by roborourke** [comment]
In future can you reference the issue in the pull request comment rather than the title? I often use the `Fixes #x` syntax to auto close the issue, at least in the case of granular issues with no follow up actions.

**Comment by jazzsequence** [comment]
I usually will attach the original issue to the PR in ZenHub, but I'm not sure how that affects the original issue when there's multiple PRs. If there's a single PR, closing/merging it will auto-close the issue the same way it would with `fixes`. (Usually.)

**Comment by roborourke** [comment]
Yeah fair, it’s a judgment call really. The thing is to reduce the amount of manual effort you need to put in when possible. Main thing really is just to use github’s built in issue cross-references as well for anyone looking who isn’t using zenhub. It’s also making sure we’re future proof if we ever move away from zenhub

**Pull request merged**
