### PR TITLE
Update XB client IDs on clone

### PR DESCRIPTION
**Pull request by roborourke**
Fixes https://github.com/humanmade/aws-analytics/issues/195

### CODE REVIEW

**Review by jazzsequence — APPROVED** [review]
Just a question --
The client ID at this point is just an arbitrary string because it's not referring to anything in ES yet?

**Comment by roborourke** [comment]
@jazzsequence correct - changing it out at this point will cause a new XB post to be created. The client ID string could technically be any rando string.

**Comment by roborourke** [comment]
Quick note - avoid pushing merge commits if you can as it makes it more complicated to backport. Was there a conflict?

**Comment by jazzsequence** [comment]
@roborourke It said that it couldn't be merged because `master` had been updated. There wasn't an indication that there was a conflict per se, but the merge button was greyed out.

**Comment by roborourke** [comment]
I'll look into it, might be a repo setting

**Pull request merged**
